import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core'

export const adrs = sqliteTable('adrs', {
  id: text('id').primaryKey(),
  planId: text('plan_id').notNull(),
  sequenceNumber: integer('sequence_number').notNull(),
  title: text('title').notNull(),
  status: text('status').notNull().default('draft'),
  decisionDate: text('decision_date').notNull().default(''),
  deciders: text('deciders').notNull().default('[]'),
  context: text('context').notNull(),
  problemStatement: text('problem_statement').notNull(),
  driverType: text('driver_type').notNull(),
  options: text('options').notNull().default('[]'),
  decisionOutcome: text('decision_outcome').notNull().default(''),
  decisionRationale: text('decision_rationale').notNull().default(''),
  positiveConsequences: text('positive_consequences').notNull().default('[]'),
  negativeConsequences: text('negative_consequences').notNull().default('[]'),
  reviewTriggers: text('review_triggers').notNull().default('[]'),
  supersededById: text('superseded_by_id').notNull().default(''),
  supersedes: text('supersedes').notNull().default('[]'),
  linkedConstraintIds: text('linked_constraint_ids').notNull().default('[]'),
  linkedNFRIds: text('linked_nfr_ids').notNull().default('[]'),
  linkedRiskIds: text('linked_risk_ids').notNull().default('[]'),
  linkedOpportunityIds: text('linked_opportunity_ids').notNull().default('[]'),
  linkedStakeholderIds: text('linked_stakeholder_ids').notNull().default('[]'),
  createdVia: text('created_via').notNull().default('manual'),
  tags: text('tags').notNull().default('[]'),
  notes: text('notes').notNull().default(''),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})
